export const AUDIT_ACTIONS = {
  TENANT_CREATED: "TENANT_CREATED",
  BILLING_STATUS_CHANGED: "BILLING_STATUS_CHANGED",
  TENANT_UPDATED: "TENANT_UPDATED",
  AGENCY_STAFF_PASSWORD_CHANGED: "AGENCY_STAFF_PASSWORD_CHANGED",
  TENANT_DELETED: "TENANT_DELETED",
} as const;
